@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 10 10:24:09 +0100 2024
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim TB_nexys_PIC_behav -key {Behavioral:sim_1:Functional:TB_nexys_PIC} -tclbatch TB_nexys_PIC.tcl -view C:/Users/rafer/Desktop/Master/PrimerCuatri/LCSE/230211copia/p2230211/p2230211.srcs/sim_1/imports/230211/p2230211/SimBehPIC.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
