# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/230211/Nexys_PIC.xdc

# IP: ip/fifo_3/fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] -quiet
